### ISSUE TITLE
A distributed application which should display a message only once on a node in a cluster

### ISSUE THREAD

**Issue by varsharain-a11y** [clusterbench/clusterbench#206]
To have a better distributable web application for testing clustering for Scenarios like 
Multiple nodes in cluster, Few nodes may start after some time or few may not start .
The application should coordinate between the nodes so that as they are started System.out.println("Application in running!") is only called exactly once across the whole cluster, whether 1 node or 5 are running.

**Comment by rhusar** [comment]
Well, the successful deployment is logged on the server log and subsequent joining of the cluster is also logged from the infinispan logger with the topology. So those messages should be used for any of the topology information.

You can also consult the `/clusterbench/debug` servlet and parse out topology information from that.
