### ISSUE TITLE
ERROR: Could not load JSF managed bean class: org.jboss.test.clusterbench.web.jsf.JsfManagedBean during deployment

### ISSUE THREAD

**Issue by mvinkler** [clusterbench/clusterbench#36]
How to reproduce:

build clusterbench from trunk
Copy clusterbench-ee7.ear to server's deployments directory and start the standalone server in the HA mode

In the server log during the deployment:
11:47:09,732 ERROR [org.jboss.as.jsf] (MSC service thread 1-8) WFLYJSF0002: Could not load JSF managed bean class: org.jboss.test.clusterbench.web.jsf.JsfManagedBean

**Comment by rhusar** [comment]
Yes, I know, I suggest lets remove the JDF stuff completely. Ok?

**Comment by mvinkler** [comment]
Yes please! Nobody I would know about.

**Comment by rhusar** [comment]
On the call we decided to keep it and fix it instead.

**Comment by rhusar** [comment]
Fixed.
