### ISSUE TITLE
Merge long time separated forks

### ISSUE THREAD

**Issue by Karm** [clusterbench/clusterbench#51]
@Karm's branch [simplified-and-pure](https://github.com/Karm/clusterbench/tree/simplified-and-pure) has been used for mod_cluster testing across Tomcat 6, Tomcat 7, Tomcat 8, JBoss AS 5, JBoss AS 7 and Wildfly for past several years.

It offers various special purpose servlets the upstream version doesn't have. There are servlets that fill memory, generate deterministic CPU load, crash JVM, invalidate sessions or send back particular HTTP response codes.

It would be great both for Clustering QE and Mod_cluster QE if we could merge these two code bases and prepare a set of maven profiles and modules so as it is possible to produce clusterbench builds for bothTomcat 6 on JDK 6 as well as for full blown Wildfly EE server on JDK 8.

**Comment by Karm** [comment]
I have a hunch, who might take a look at this in November, @S4n60w3n :-)

**Comment by rhusar** [comment]
@mvinkler wdyt?

**Comment by rhusar** [comment]
@honza-kasik Is this done now? What are we missing?

**Comment by honza-kasik** [comment]
@rhusar  Parity with features used in mod_cluster tests was almost achieved. We just need to migrate https://github.com/Karm/clusterbench/blob/simplified-and-pure/clusterbench-common/src/main/java/org/jboss/test/clusterbench/common/jvmroute/CommonHTTPCodeServlet.java + the child servlet.

**Comment by rhusar** [comment]
@honza-kasik Ah, that one looks interesting - porting it right now.

**Comment by rhusar** [comment]
@honza-kasik Opened https://github.com/clusterbench/clusterbench/pull/355 - please review.

**Comment by rhusar** [comment]
@honza-kasik With the https://github.com/clusterbench/clusterbench/pull/355 merged, it appears that this issue is resolved. Closing!
